#!/bin/bash

test "$#" -lt 2 \
  && echo "Usage: $0 [old_tf_version] [new_tf_version]" >&2 \
  && exit 1

old="$1"
new="$2"

find . \
  -name 'node_modules' -type d -prune \
  -o -name 'main.tf' \
  -exec sed -i "s/~> $old/~> $new/g" {} +
